In [1]:
import pandas as pd
import numpy as np

In [14]:
df=pd.DataFrame()
df=pd.read_csv('sales_data.csv')
print(df)

              Date  Day     Month  Year  Customer_Age       Age_Group  \
0       2013-11-26   26  November  2013            19     Youth (<25)
1       2015-11-26   26  November  2015            19     Youth (<25)
2       2014-03-23   23     March  2014            49  Adults (35-64)
3       2016-03-23   23     March  2016            49  Adults (35-64)
4       2014-05-15   15       May  2014            47  Adults (35-64)
...            ...  ...       ...   ...           ...             ...
113031  2016-04-12   12     April  2016            41  Adults (35-64)
113032  2014-04-02    2     April  2014            18     Youth (<25)
113033  2016-04-02    2     April  2016            18     Youth (<25)
113034  2014-03-04    4     March  2014            37  Adults (35-64)
113035  2016-03-04    4     March  2016            37  Adults (35-64)

       Customer_Gender         Country             State Product_Category  \
0                    M          Canada  British Columbia      Accessories
1                    M          Canada  British Columbia      Accessories
2                    M       Australia   New South Wales      Accessories
3                    M       Australia   New South Wales      Accessories
4                    F       Australia   New South Wales      Accessories
...                ...             ...               ...              ...
113031               M  United Kingdom           England         Clothing
113032               M       Australia        Queensland         Clothing
113033               M       Australia        Queensland         Clothing
113034               F          France     Seine (Paris)         Clothing
113035               F          France     Seine (Paris)         Clothing

       Sub_Category              Product  Order_Quantity  Unit_Cost  \
0        Bike Racks  Hitch Rack - 4-Bike               8         45
1        Bike Racks  Hitch Rack - 4-Bike               8         45
2        Bike Racks  Hitch Rack - 4-Bike              23         45
3        Bike Racks  Hitch Rack - 4-Bike              20         45
4        Bike Racks  Hitch Rack - 4-Bike               4         45
...             ...                  ...             ...        ...
113031        Vests      Classic Vest, S               3         24
113032        Vests      Classic Vest, M              22         24
113033        Vests      Classic Vest, M              22         24
113034        Vests      Classic Vest, L              24         24
113035        Vests      Classic Vest, L              23         24

        Unit_Price  Profit  Cost  Revenue
0              120     590   360      950
1              120     590   360      950
2              120    1366  1035     2401
3              120    1188   900     2088
4              120     238   180      418
...            ...     ...   ...      ...
113031          64     112    72      184
113032          64     655   528     1183
113033          64     655   528     1183
113034          64     684   576     1260
113035          64     655   552     1207

[113036 rows x 18 columns]

In [9]:
df.isnull()

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113031,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113032,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113033,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113034,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113035,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
df.isnull().sum()

Date                0
Day                 0
Month               0
Year                0
Customer_Age        0
Age_Group           0
Customer_Gender     0
Country             0
State               0
Product_Category    0
Sub_Category        0
Product             0
Order_Quantity      0
Unit_Cost           0
Unit_Price          0
Profit              0
Cost                0
Revenue             0
dtype: int64

In [21]:
col=['Date','Day','Month','Year','Customer_Age','Age_Group','Customer_Gender','Country','State','Product_Category','Sub_Category','Product','Order_Quantity','Unit_Cost','Unit_Price','Profit','Cost','Revenue']
df[col]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113031,2016-04-12,12,April,2016,41,Adults (35-64),M,United Kingdom,England,Clothing,Vests,"Classic Vest, S",3,24,64,112,72,184
113032,2014-04-02,2,April,2014,18,Youth (<25),M,Australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113033,2016-04-02,2,April,2016,18,Youth (<25),M,Australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113034,2014-03-04,4,March,2014,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",24,24,64,684,576,1260
113035,2016-03-04,4,March,2016,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",23,24,64,655,552,1207

In [15]:
# import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [16]:
# plt.barchart('Date')

<class 'AttributeError'>: module 'matplotlib.pyplot' has no attribute 'barchart'